services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: ec2-ecr-learning-app
      APP_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      AWS_REGION: eu-west-1
      ECR_REPOSITORY: ec2-ecr-learning-app
    ports:
      - "${APP_HOST_PORT:-3000}:3000"
