services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: simple-app
      APP_ENV: development
      HOST: 0.0.0.0
      PORT: 4000
      AWS_REGION: eu-north-1
      ECR_REPOSITORY: simple-app
    ports:
      - "${APP_HOST_PORT:-4000}:4000"
