# Default values for simple-app.

replicaCount: 1

image:
  repository: simple-app
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

app:
  name: simple-app
  environment: development
  host: "0.0.0.0"
  port: "4000"
  awsRegion: eu-north-1
  ecrRepository: simple-app

imagePullSecrets: []

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000
  containerPort: 4000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
